### ISSUE TITLE
how to deploy to vercel?

### ISSUE THREAD

**Issue by makerjackie** [onggiabayluon/fullstack-comic-app#17]
Hello, 

I was wondering if you could kindly provide some guidance on how to deploy your repository to Vercel. I'm interested in using your project but am new to the deployment process and wanted to ensure proper implementation. Thank you for your help in advance.

**Comment by onggiabayluon** [comment]
Its actually pretty easy: 
- I assume you already cloned this respository to your GitHub and had a vercel account.

- On [Vercel create project page](https://vercel.com/new) choose your cloned respo:
![Screenshot_2023-04-26-21-32-06-374_com android chrome](https://user-images.githubusercontent.com/70091587/234609044-59ba99e1-1cf2-450a-9926-896355b45674.jpg)
Then it will automatically deploy as i remember correctly

- set environment variables: after the deployment > go to settings tab 

![Screenshot_2023-04-26-21-34-32-647_com android chrome](https://user-images.githubusercontent.com/70091587/234610213-76723972-2022-4e5e-be31-cee677154111.jpg)

![Screenshot_2023-04-26-21-34-48-240_com android chrome-edit](https://user-images.githubusercontent.com/70091587/234610298-223e4c47-fdaf-4185-ad4b-97a11442436f.jpg)

There are some env you need to set:

BACKEND_REVALIDATE_SECRET=BACKEND_REVALIDATE_SECRET
You can use the same env as me. This is a revalidate secret code for on-demand ISR, you can go read it on nextjs official page

NEXT_PUBLIC_BASE_API_ENDPOINT=localhost:8080/
This is the backend url, change accordingly to your needs 

NEXT_PUBLIC_REVALIDATE_IN_1_HOUR=3600
NEXT_PUBLIC_REVALIDATE_IN_1_MINUTE=600

Finish and wait for the server to redeploy.
Make sure you run the backend along side the frontend

**Comment by makerjackie** [comment]
thx for your reply! can I deploy backend to vercel too? or I should use other platform like fly.io

**Comment by onggiabayluon** [comment]
No, Backend need to deploy separately, so if fly.io support deployment for python django mysql then u can go for it

**Comment by makerjackie** [comment]
Thank you for your patient reply!
